---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-pipeline-1
spec:
  template:
    metadata:
      labels:
        app: demo-pipeline-1
        id: "1"
    spec:
      containers:
      - name: demo-pipeline-1
        image: ggriffiths/demo-go-pipeline
        ports:
        - containerPort: 8080